## Basic Modules
-> Math <br>
-> Random <br>
-> statistics
#### i can get unlabeled data from a Series or DataFrame as a np.array object by calling .values or .to_numpy()

# MAth library Function

In [2]:
# Write a python for calculating the area of circle
import math
radius = float(input("Enter Radius ="))
area = math.pi*radius*radius
print(area)

Enter Radius =78
19113.4497044403


In [3]:
# defult pi value just calling math library function
math.pi

3.141592653589793

In [6]:
# eils(x) --- Returns the samallest integer grater than or equal to x
x = [7,8,2,9,10]
math.ceil(x)

TypeError: must be real number, not list

In [7]:
# Round a number upward to its nearest integer
math.ceil(100.34837934875)

101

In [8]:
x = 10
y =12
math.copysign(x,y)

10.0

In [9]:
math.copysign(y,x)

12.0

In [11]:
# Return the absoulte value of x
x = 12.94857984
math.fabs(x)

12.94857984

In [12]:
# Returns the samallest integer grater than or equal to x
math.ceil(x)

13

In [13]:
# Return the factorial of x
math.factorial(x)

TypeError: 'float' object cannot be interpreted as an integer

In [14]:
math.factorial(4)

24

In [15]:
# Return the largest integer less than or equal to x
math.floor(x)

12

In [18]:
# Returns the reminder when x is divided by y
math.fmod(x,y)

0.9485798400000007

In [19]:
math.log10(x)

1.1122221389599145

In [20]:
math.exp(x)

420239.40509697655

In [21]:
math.expm1(x)

420238.40509697655

In [22]:
math.isinf(x)

False

In [23]:
# Returns the fractorial and integer parts of x
z = 10.3
math.modf(z)

(0.3000000000000007, 10.0)

In [24]:
# Returns x raised to the power y
x = 2
y = 3
math.pow(x,y)

8.0

In [25]:
# Returns the squre root of x
math.sqrt(x)

1.4142135623730951

In [26]:
math.cos(x)

-0.4161468365471424

In [27]:
# converts angle x from degrees to radians
math.degrees(x)

114.59155902616465

In [28]:
# Converts angle x from degrees to radians
math.radians(x)

0.03490658503988659

In [29]:
# Returns the inverse hyperbolic cosine of x 
math.acosh(x)

1.3169578969248166

In [30]:
math.e

2.718281828459045

## Random Module

In [31]:
import random

In [32]:
random.seed(10)

In [33]:
# Method returns a random floating number between 0 and 1
random.random()

0.5714025946899135

In [34]:
random.uniform(10,30)

18.577781093502292

In [38]:
random.randint(2,30)

8

In [41]:
random.choice([2,4,6,7,8,9])

6

In [44]:
numbers = [2,4,3,8,9,20]
random.shuffle(numbers)
numbers

[20, 9, 3, 4, 8, 2]

### Concept of Array
-> 0D ( zero-dimensional) - Scalar - A single element <br>
-> 1D ( one -dimensional) - Vector - A list of integers <br>
-> 2D (two-dimensional) - MAtrix - A spreadsheet of data <br>
-> 3D (three-dimensional) - Tensor - Storing a color image

In [45]:
## Creating arrays:
import numpy as np

In [46]:
a = np.array([1,2,4])
a

array([1, 2, 4])

In [47]:
# Create a 2 * 2 matirx = 2 rows and 2 columns
b = np.array([[3,5],[10,34]])
b

array([[ 3,  5],
       [10, 34]])

In [48]:
# Array indexing and Slicing
# acces elements
a[0]

1

In [49]:
b[0]

array([3, 5])

In [50]:
b[0,1] # first row and 2nd cloumns

5

In [51]:
b[1,1] # 2nd row and 2 columns element

34

In [52]:
# Slicing
a[0:2] # start form 0 end befor 2 means 1

array([1, 2])

In [53]:
c = [7,5,9,14,53,23,63,15,17]
c[3:7] # start from postion 3 and end befor 7 position means position no 6

[14, 53, 23, 63]

In [54]:
c[-1:]

[17]

In [59]:
# MAthematical functions
# compute the sine of each element
a = [2,4,7,9]
np.sin(a)

array([ 0.90929743, -0.7568025 ,  0.6569866 ,  0.41211849])

In [61]:
# ok done. understand
math.sin(a)

TypeError: must be real number, not list

In [62]:
# compute the mean of the array
np.mean(a)

5.5

# Random number eneration

In [64]:
# Random number eneration
random_array = np.random.rand()

In [65]:
random_array

0.014190953336121082

In [67]:
# generate a random array
randomArray = np.random.rand(3,2) # 3 rows and 2 cols
randomArray

array([[0.37476198, 0.29299542],
       [0.03379047, 0.98894565],
       [0.70827219, 0.82311077]])

In [68]:
numpyarray = np.random.rand(4,3) # 4 rows and every row 3 cols
numpyarray

array([[0.54015788, 0.30880693, 0.95765811],
       [0.0662308 , 0.53289943, 0.17211675],
       [0.83890367, 0.11493608, 0.81604276],
       [0.08524455, 0.53615555, 0.28311176]])

# Array Creation Functions

In [72]:
# np.array()
# creates an array from a list or tuple
a = (3,5,7,92,56,12,14,74,48,82,53,36,62)
np.array(a)

array([ 3,  5,  7, 92, 56, 12, 14, 74, 48, 82, 53, 36, 62])

In [75]:
# np.zeros()
# creates an array filled with zeros
np.zeros(5) # 1D array with 0 values

array([0., 0., 0., 0., 0.])

In [77]:
# np.ones()
# Creates an array with a range of values
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.linspace(5,3)

array([5.        , 4.95918367, 4.91836735, 4.87755102, 4.83673469,
       4.79591837, 4.75510204, 4.71428571, 4.67346939, 4.63265306,
       4.59183673, 4.55102041, 4.51020408, 4.46938776, 4.42857143,
       4.3877551 , 4.34693878, 4.30612245, 4.26530612, 4.2244898 ,
       4.18367347, 4.14285714, 4.10204082, 4.06122449, 4.02040816,
       3.97959184, 3.93877551, 3.89795918, 3.85714286, 3.81632653,
       3.7755102 , 3.73469388, 3.69387755, 3.65306122, 3.6122449 ,
       3.57142857, 3.53061224, 3.48979592, 3.44897959, 3.40816327,
       3.36734694, 3.32653061, 3.28571429, 3.24489796, 3.20408163,
       3.16326531, 3.12244898, 3.08163265, 3.04081633, 3.        ])

In [81]:
# Creates an identity matix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
# create an array of ones
np.ones(4) # 1D one array

array([1., 1., 1., 1.])

In [84]:
np.ones((3,4)) # 3 rows and 4 cols one array. but be careful wehn we use at a time rows and cols must be use brackets

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
# Create an array with random values
np.random.random((3,4))

array([[0.04071774, 0.34644703, 0.60991342, 0.81032347],
       [0.68461239, 0.47575439, 0.94080864, 0.46397478],
       [0.66067778, 0.46372769, 0.78266171, 0.95951615]])

In [86]:
np.random.rand(3)

array([0.71261514, 0.4100203 , 0.2709024 ])

In [87]:
np.random.rand(3,3)

array([[0.81858104, 0.2898834 , 0.82944043],
       [0.98736481, 0.64086756, 0.57519253],
       [0.86073103, 0.6409102 , 0.01439696]])

# Array Manipulation Functions

In [88]:
# reshape an array without changing it s data
# np.reshape()
randomarray = np.random.rand(3,4) # 3 rows and 4 cols
randomarray

array([[0.17352813, 0.63148151, 0.02118556, 0.91922572],
       [0.83755881, 0.73862827, 0.68355033, 0.06008455],
       [0.74094753, 0.21872148, 0.20368803, 0.33457317]])

In [92]:
np.reshape(randomarray,(4,3)) #  4 rows and 3 cols

array([[0.17352813, 0.63148151, 0.02118556],
       [0.91922572, 0.83755881, 0.73862827],
       [0.68355033, 0.06008455, 0.74094753],
       [0.21872148, 0.20368803, 0.33457317]])

In [96]:
np.reshape(np.arange(10),(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [99]:
# Flattens a multi-dimensional array into 1D array
randomarray.flatten()

array([0.17352813, 0.63148151, 0.02118556, 0.91922572, 0.83755881,
       0.73862827, 0.68355033, 0.06008455, 0.74094753, 0.21872148,
       0.20368803, 0.33457317])

In [102]:
# Joins two or more array along an existing axis
a = np.random.rand(3,4)
b = np.random.rand(3,4)
c = np.random.rand(3,4)
np.concatenate((a,b,c), axis=0)

array([[0.60772731, 0.5560407 , 0.67099771, 0.00096225],
       [0.12793552, 0.27038564, 0.42825945, 0.11707321],
       [0.60266086, 0.10882042, 0.9524474 , 0.87153134],
       [0.27621554, 0.51053248, 0.35659609, 0.29201813],
       [0.34087795, 0.26596059, 0.2710172 , 0.22640389],
       [0.19907391, 0.61693443, 0.6144197 , 0.6313069 ],
       [0.19976571, 0.56163509, 0.88338379, 0.66092495],
       [0.60508169, 0.26418894, 0.88374486, 0.31100008],
       [0.51443322, 0.49366355, 0.4828785 , 0.3388596 ]])

In [103]:
np.concatenate((a,b,c), axis=1)

array([[0.60772731, 0.5560407 , 0.67099771, 0.00096225, 0.27621554,
        0.51053248, 0.35659609, 0.29201813, 0.19976571, 0.56163509,
        0.88338379, 0.66092495],
       [0.12793552, 0.27038564, 0.42825945, 0.11707321, 0.34087795,
        0.26596059, 0.2710172 , 0.22640389, 0.60508169, 0.26418894,
        0.88374486, 0.31100008],
       [0.60266086, 0.10882042, 0.9524474 , 0.87153134, 0.19907391,
        0.61693443, 0.6144197 , 0.6313069 , 0.51443322, 0.49366355,
        0.4828785 , 0.3388596 ]])

In [108]:
# Splits an array into multiple sub-arrays
np.split(a,[2,3])

[array([[0.60772731, 0.5560407 , 0.67099771, 0.00096225],
        [0.12793552, 0.27038564, 0.42825945, 0.11707321]]),
 array([[0.60266086, 0.10882042, 0.9524474 , 0.87153134]]),
 array([], shape=(0, 4), dtype=float64)]

In [109]:
# Stacks arrays in sequence horizontally ( column-wise)
np.hstack(a)

array([0.60772731, 0.5560407 , 0.67099771, 0.00096225, 0.12793552,
       0.27038564, 0.42825945, 0.11707321, 0.60266086, 0.10882042,
       0.9524474 , 0.87153134])

In [110]:
np.vstack(a)

array([[0.60772731, 0.5560407 , 0.67099771, 0.00096225],
       [0.12793552, 0.27038564, 0.42825945, 0.11707321],
       [0.60266086, 0.10882042, 0.9524474 , 0.87153134]])

In [112]:
x = np.arange(4,10,4)
x

array([4, 8])

In [117]:
add = np.random.rand(3,3)
add

array([[0.71326384, 0.16452496, 0.0284465 ],
       [0.98018796, 0.37258208, 0.71648393],
       [0.25149381, 0.39696608, 0.21714821]])

# MAthematical Operations

In [118]:
# Element wise addition
np.add(add,add)

array([[1.42652767, 0.32904992, 0.05689299],
       [1.96037593, 0.74516416, 1.43296787],
       [0.50298762, 0.79393215, 0.43429642]])

In [119]:
# Element wise subtraction of array
np.subtract(add,add)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [120]:
# Element wise multiplication of array
np.multiply(add,add)

array([[5.08745299e-01, 2.70684618e-02, 8.09203145e-04],
       [9.60768444e-01, 1.38817405e-01, 5.13349229e-01],
       [6.32491362e-02, 1.57582066e-01, 4.71533452e-02]])

In [121]:
# Element wise divide
np.divide(add,add)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [122]:
# Dot products of two array
np.dot(add,add)

array([[0.6771648 , 0.18994105, 0.14434645],
       [1.24452437, 0.58450261, 0.45041519],
       [0.62309424, 0.27547993, 0.33872728]])

In [123]:
# Mean of array elements along a given axis
np.mean(add)

0.42678859584744294

In [124]:
# STD of array elements along a given axis
np.std(add)

0.2940532906125735

In [125]:
# Median of array elements along a given axis
np.median(add)

0.3725820785261488

In [126]:
# Variance of array elements along a given axis
np.var(add)

0.08646733772008262

# Linear Algebra Functions

In [130]:
# computs the inverse of a matrix
matrics = np.random.rand(4,2) # 4 rows and 2 cols
matrics

array([[0.77743368, 0.9611942 ],
       [0.22157658, 0.13805088],
       [0.83058843, 0.34015721],
       [0.11349097, 0.92300526]])

In [132]:
np.linalg.inv(matrics)

LinAlgError: Last 2 dimensions of the array must be square

In [134]:
matrics = np.random.rand(4,4) # for invers matrics must be square matrics
matrics

array([[0.97513058, 0.33172409, 0.45406196, 0.62339373],
       [0.71933181, 0.12267259, 0.00907457, 0.70512412],
       [0.87073922, 0.49976913, 0.59560271, 0.67724733],
       [0.31942087, 0.07986327, 0.96491748, 0.38520752]])

In [135]:
np.linalg.inv(matrics)

array([[ 4.11925158, -1.09716866, -2.3927734 , -0.45112335],
       [-2.47546804, -1.01531861,  4.11108006, -1.36316419],
       [ 0.3487307 , -0.63955574, -0.23834498,  1.02539055],
       [-3.77607447,  2.72233456,  1.72883615,  0.68417071]])

In [136]:
# computes the eignevalues and eignevectors of a matix
np.linalg.eig(matrics)

(array([ 2.17471951+0.j        ,  0.19569217+0.j        ,
        -0.14589915+0.35093908j, -0.14589915-0.35093908j]),
 array([[-0.55745777+0.j        ,  0.68041165+0.j        ,
          0.02848628-0.12871389j,  0.02848628+0.12871389j],
        [-0.35038305+0.j        , -0.1652609 +0.j        ,
          0.7228289 +0.j        ,  0.7228289 -0.j        ],
        [-0.60834128+0.j        , -0.07205297+0.j        ,
         -0.08249772-0.34040389j, -0.08249772+0.34040389j],
        [-0.443163  +0.j        , -0.71030781+0.j        ,
         -0.30331378+0.49543891j, -0.30331378-0.49543891j]]))

In [137]:
# computes the determinent of a matix
np.linalg.det(matrics)

0.06147217897717309

In [138]:
# computes the singular value decomposition of a matix
np.linalg.svd(matrics)

(array([[-0.57109316, -0.17308357,  0.21889859,  0.77199617],
        [-0.40092601, -0.55526691, -0.69319909, -0.22452621],
        [-0.60032316,  0.0059584 ,  0.53497893, -0.59445281],
        [-0.39079795,  0.81344037, -0.43052988,  0.01535437]]),
 array([2.23125688, 0.79066653, 0.27351886, 0.12739383]),
 array([[-0.6690593 , -0.25539927, -0.44709858, -0.5359419 ],
        [-0.38345141, -0.07283751,  0.89142788, -0.23025213],
        [ 0.15765447,  0.8063789 , -0.01348303, -0.56983887],
        [ 0.61682229, -0.52841175,  0.07264568, -0.57882113]]))

In [141]:
# Solve a linear matrix equation
np.linalg.solve(matrics,matrics)

array([[ 1.00000000e+00, -5.69268902e-17,  0.00000000e+00,
         0.00000000e+00],
       [-8.73764830e-17,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 4.75627301e-18, -5.88826547e-18,  1.00000000e+00,
         0.00000000e+00],
       [ 7.48797970e-17,  4.80722981e-17, -1.85257694e-17,
         1.00000000e+00]])

# Solving a system of Linear Equations

In [142]:
a = np.array([[2,3],[4,1]])
#x = np.array([x,y])
b = np.array([5,6])
x = np.linalg.solve(a,b)
x

array([1.3, 0.8])

# Numpy Modules woth Pandas DataFrame

In [143]:
import numpy as np

### 1. Compute the sum, mean and standard deviation of a 2D array created from np.random.randn(4,4)

In [144]:
array = np.random.randn(4,4)
array

array([[ 1.62117471,  0.10591548, -0.33662562,  0.59980284],
       [-0.20930809, -0.24939246,  0.60369192,  1.00380895],
       [ 0.75448457, -0.12450249, -0.41763911, -0.24192165],
       [ 0.19676898,  0.64303069,  1.61229084,  1.97007482]])

In [145]:
# sum 
np.sum(array)

7.531654372786506

In [146]:
# mean
np.mean(array)

0.47072839829915664

In [147]:
# Standard Deviation
np.std(array)

0.7414430354661847

### 2. Compute the system of linear equations
3x + 2y = 5 <br>
x - y = 1

In [148]:
A = np.array([[3,2],[1,-1]])
b = np.array([5,1])
x = np.linalg.solve(A,b)
x

array([1.4, 0.4])

### 3. Compute the inverse of the matrix

In [149]:
inversematirx = np.array([[1,2],[2,0]])
np.linalg.inv(inversematirx)

array([[ 0.  ,  0.5 ],
       [ 0.5 , -0.25]])

### 4. Find the eigenvalues and eignevectors of the matix

In [150]:
eigenvalue = np.array([[2,0],[0,3]])
np.linalg.eig(eigenvalue)

(array([2., 3.]),
 array([[1., 0.],
        [0., 1.]]))

### 5 Generate an array of 10 random integers between 1 and 100

In [161]:
randomarray = np.arange(1,100,10)
randomarray

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [165]:
mean = 0 
std = 1 
randomNum = np.random.normal(loc=mean, scale=std, size=(5, 5))
randomNum


array([[-0.44116856, -0.80084584, -0.03610492, -0.88255311, -1.78479659],
       [-1.27928555, -0.13308323, -0.633759  ,  1.18425924, -0.75115263],
       [-0.59510122,  0.69766676,  0.13186088, -0.09172636, -1.89750911],
       [ 0.62087881,  0.57485969,  0.27282648, -0.52155995, -1.14790953],
       [ 0.15172856, -0.84591278, -0.26925762, -0.66391801, -0.26891407]])