## HOME Work - 05
Name: Subena Khatun <br>
ID: 20241373<br>
Batch: 13 <br>
Section: B

In [1]:
# import modules
import numpy as np

### 1. Compute the sum, mean and standard deviation of a 2D array created from np.random.randn(4,4)

In [2]:
array = np.random.randn(4,4)
array

array([[-1.59555479, -0.60967465,  1.31754293,  0.78863095],
       [-0.44259269,  2.01830616, -2.52839107,  0.93400929],
       [-1.50940561, -1.45855196, -1.37796747,  0.75105204],
       [ 1.0468288 ,  1.04408469, -2.14906233, -0.07297589]])

In [3]:
# sum , mean and Standard Deviation
sum = np.sum(array)
mean = np.mean(array)
stdev = np.std(array)
print(f"Sum of Array= {sum}, \nMean = {mean} \nStandard Deviation = {stdev}")

Sum of Array= -3.8437215965473253, 
Mean = -0.24023259978420783 
Standard Deviation = 1.3593395085563065


### 2. Compute the system of linear equations
3x + 2y = 5 <br>
x - y = 1

In [4]:
A = np.array([[3,2],[1,-1]])
b = np.array([5,1])
x = np.linalg.solve(A,b)
x

array([1.4, 0.4])

### 3. Compute the inverse of the matrix

In [5]:
inversematirx = np.array([[1,2],[2,0]])
np.linalg.inv(inversematirx)

array([[ 0.  ,  0.5 ],
       [ 0.5 , -0.25]])

### 4. Find the eigenvalues and eignevectors of the matix

In [6]:
eigenvalue = np.array([[2,0],[0,3]])
np.linalg.eig(eigenvalue)

(array([2., 3.]),
 array([[1., 0.],
        [0., 1.]]))

### 5 Generate an array of 10 random integers between 1 and 100

In [7]:
randomarray = np.arange(1,100,10)
randomarray

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Cretae an array of a random numbers from a normal distribution with mean 0 and standard deviation 1.

In [8]:
mean = 0 
std = 1 
randomNum = np.random.normal(loc=mean, scale=std, size=(5, 5))
randomNum

array([[-0.25004636, -1.55205476,  1.44028341,  0.26481798,  0.52119059],
       [-1.08401161,  1.9824058 , -0.25386641,  1.97411981, -0.57401618],
       [-0.44887596, -0.13211933, -1.3843906 , -0.45276016, -1.75552622],
       [-0.69206658, -0.2329867 , -0.38945949, -0.3428635 ,  0.52099035],
       [-1.43271501, -0.84850137, -1.04632046,  1.13054496,  0.85706693]])