In [1]:
print("HEllo Numpy? Let's get started!")

HEllo Numpy? Let's get started!


# Numpy Day-01
1. Creaitn numpy array
    i. np.array <br>
    ii. 1D array<br>
    iii. 2D array<br>
    iv. 3D array<br>
    v. dtype<br>
    vi. np.arange<br>
    vii. reshape<br>
    viii. np.ones <br>
    ix. np.zeros<br>
    x. np.random<br>
    xi. np.linespace<br>
    xii. np.identity
2. Array Attributes
    i. ndim<br>
    ii.shape<br>
    iii. size<br>
    iv. itemsize<br>
    v. dtype
3. Changing Datatype
    i. astype(np.int32)
4. Array operations
    i. Scalar operations<br>
    ii. Arithmatic operation (+,-,**,/,%)<br>
    iii. rational (==,!=,<=,>=)<br>
    iv. Vector<br>
5. Array Functions
    i. max/min/sum/mod<br>
    ii. mean/median/mode/std/var<br>
    iii. Trigonmatirc function<br>
    iv. dot product<br>
    v. log and exponents<br>
    vi. round/floor/ceil<br>
6. Indexing and slicing
7. reshaping
8. Stacking
9. spliting



In [2]:
print("Hello wolrd")

Hello wolrd


In [3]:
# 1. Creating Numpy array

# import numpy
import numpy as np
print(np.__version__)

2.3.5


In [4]:
# create an array using np.array
np.array([10,40,30,50,60,100,30,20])
# 1D array or vector
d1 = np.array([40,20,90,80,30])
d1

array([40, 20, 90, 80, 30])

In [5]:
# 2D array = MAtrix = row and column format
mat = np.array([[10,20,30,40],[50,60,79],[5,6,7]])
mat

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [6]:
mat = np.array([[10,20,30,40],[50,60,79,55],[5,6,7,60]])
mat

array([[10, 20, 30, 40],
       [50, 60, 79, 55],
       [ 5,  6,  7, 60]])

In [7]:
# check dimention of mat array
mat.ndim

2

In [8]:
# how many rows and coumns?
mat.shape

(3, 4)

In [9]:
# make empty array
em = []

In [10]:
for i in range(1,10):
    em.append(i)
em

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
# convert list into array
nparray = np.array(em)
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 3D array
array3d = np.array([[[10,20,30,10],[40,50,60,43],[70,80,90,34]],[[1,2,3,4],[5,6,7,8],[9,10,1,12]],[[10,20,30,10],[40,50,60,43],[70,80,90,34]]])
array3d.shape

(3, 3, 4)

In [13]:
array3d1 = np.array([[[10,20,30,10],[40,50,60,43]],[[1,2,3,4],[5,6,7,8]],[[10,20,30,10],[40,50,60,43]]])
# 3 rows ---3d, 2 rows---2D, 4 columns --- 2D
array3d1.shape

(3, 2, 4)

In [14]:
# reshape 3D columns into 2D
array3d1.reshape(2,4,3)

array([[[10, 20, 30],
        [10, 40, 50],
        [60, 43,  1],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [ 8, 10, 20],
        [30, 10, 40],
        [50, 60, 43]]])

In [15]:
array3d1.reshape(4,2,3)

array([[[10, 20, 30],
        [10, 40, 50]],

       [[60, 43,  1],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [ 8, 10, 20]],

       [[30, 10, 40],
        [50, 60, 43]]])

In [16]:
# anyhow all products number = total itemsize
array3d1.reshape(4,3,2)

array([[[10, 20],
        [30, 10],
        [40, 50]],

       [[60, 43],
        [ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8],
        [10, 20]],

       [[30, 10],
        [40, 50],
        [60, 43]]])

In [17]:
# check how many iteams
array3d1.size

24

In [18]:
# check data types
array3d.dtype

dtype('int64')

In [19]:
# checnge dtaype 
array3d = array3d.astype("int32")
array3d

array([[[10, 20, 30, 10],
        [40, 50, 60, 43],
        [70, 80, 90, 34]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10,  1, 12]],

       [[10, 20, 30, 10],
        [40, 50, 60, 43],
        [70, 80, 90, 34]]], dtype=int32)

In [20]:
array3d.dtype

dtype('int32')

In [21]:
# Different ways of make array
# zero arra--- all values are zero
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# one array --- all values are one
ones = np.ones((4,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# identity array --- only digonal value 1 rest of them 0
ideti = np.identity((10,4))
ideti

TypeError: 'tuple' object cannot be interpreted as an integer

In [24]:
# identity is a squre shape matrix that's the reason it does not allow tuple
ideti = np.identity((4))
ideti

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
# as like python range start,end,step
arange = np.arange(1,18,2)
arange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [26]:
# make random number from 0 to 1 array
rarray  = np.random.random(2)
rarray

array([0.371451  , 0.70041382])

In [27]:
# create an array between 10 to 5 , 10 numbers
np.linspace(10,5,10)

array([10.        ,  9.44444444,  8.88888889,  8.33333333,  7.77777778,
        7.22222222,  6.66666667,  6.11111111,  5.55555556,  5.        ])

In [28]:
# It's just crerate lower to upper value number not upper to lower value
np.arange(-10,30,3)

array([-10,  -7,  -4,  -1,   2,   5,   8,  11,  14,  17,  20,  23,  26,
        29])

In [29]:
# using reshape
np.linspace(10,5,10).reshape(2,5)

array([[10.        ,  9.44444444,  8.88888889,  8.33333333,  7.77777778],
       [ 7.22222222,  6.66666667,  6.11111111,  5.55555556,  5.        ]])

 ### Array operations
    i. Scalar operations<br>
    ii. Arithmatic operation (+,-,**,/,%)<br>
    iii. rational (==,!=,<=,>=)<br>
    iv. Vector<br>

In [30]:
arr1 = np.random.random(12).reshape(3,4)
arr1

array([[0.89830286, 0.23232363, 0.77738361, 0.34867721],
       [0.72877363, 0.2001946 , 0.86203161, 0.97204083],
       [0.57914775, 0.58333872, 0.10055531, 0.64618768]])

In [31]:
# apply scalar opetion on arr1
5*arr1

array([[4.49151429, 1.16161815, 3.88691803, 1.74338606],
       [3.64386814, 1.00097299, 4.31015807, 4.86020414],
       [2.89573877, 2.91669359, 0.50277655, 3.23093838]])

In [32]:
# Add 5 for every elements of array
5+arr1

array([[5.89830286, 5.23232363, 5.77738361, 5.34867721],
       [5.72877363, 5.2001946 , 5.86203161, 5.97204083],
       [5.57914775, 5.58333872, 5.10055531, 5.64618768]])

In [33]:
# arithmatich operations
arra2 = np.arange(2,20,3).reshape(2,3)
arra2

array([[ 2,  5,  8],
       [11, 14, 17]])

In [34]:
arra3 = np.random.random(6).reshape(2,3)
arra3

array([[0.57415117, 0.70020576, 0.24278924],
       [0.40187675, 0.17039149, 0.67205156]])

In [35]:
# now add arra2 + arra3
arra2 + arra3

array([[ 2.57415117,  5.70020576,  8.24278924],
       [11.40187675, 14.17039149, 17.67205156]])

In [36]:
arra2 * arra3

array([[ 1.14830234,  3.50102882,  1.94231391],
       [ 4.42064425,  2.38548092, 11.42487649]])

In [37]:
arra2 ** arra3

array([[1.48880125, 3.08619118, 1.65676355],
       [2.62126849, 1.56779931, 6.71313089]])

In [38]:
arra2 / arra3

array([[ 3.48340315,  7.14075813, 32.95038962],
       [27.371576  , 82.16372581, 25.29567827]])

In [39]:
arra2 % arra3

array([[0.27754649, 0.09855965, 0.23074437],
       [0.14932775, 0.02789749, 0.19871104]])

In [40]:
arra2 - arra3

array([[ 1.42584883,  4.29979424,  7.75721076],
       [10.59812325, 13.82960851, 16.32794844]])

In [41]:
# rational operatiors
arra2 == 3

array([[False, False, False],
       [False, False, False]])

In [42]:
arra2 >= arra3

array([[ True,  True,  True],
       [ True,  True,  True]])

In [43]:
# vectors operators
varray = arra3**arra2
varray

array([[3.29649567e-01, 1.68317165e-01, 1.20735633e-05],
       [4.41592505e-05, 1.73888457e-11, 1.16370814e-03]])

### 5. Array Functions
    i. max/min/sum/mod<br>
    ii. mean/median/mode/std/var<br>
    iii. Trigonmatirc function<br>
    iv. dot product<br>
    v. log and exponents<br>
    vi. round/floor/ceil<br>

In [44]:
arra1 = np.random.random(15).reshape(3,5)
arra2 = np.arange(10,25,1).reshape(3,5)
arra3 = np.linspace(20,5,15).reshape(3,5)

In [45]:
print("Array 1",arra1)
print("Array 2",arra2)
print("Array 3",arra3)

Array 1 [[0.90549454 0.43634387 0.9745096  0.71109554 0.69888019]
 [0.93958678 0.10461072 0.80270623 0.805102   0.18390549]
 [0.15532507 0.08428724 0.53696381 0.94550207 0.36660984]]
Array 2 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Array 3 [[20.         18.92857143 17.85714286 16.78571429 15.71428571]
 [14.64285714 13.57142857 12.5        11.42857143 10.35714286]
 [ 9.28571429  8.21428571  7.14285714  6.07142857  5.        ]]


In [46]:
np.sum(arra1)

np.float64(8.65092299077381)

In [47]:
np.max(arra2)

np.int64(24)

In [48]:
np.mean(arra3)

np.float64(12.5)

In [49]:
np.round(arra3)

array([[20., 19., 18., 17., 16.],
       [15., 14., 12., 11., 10.],
       [ 9.,  8.,  7.,  6.,  5.]])

In [50]:
np.median(arra3)

np.float64(12.5)

In [51]:
np.std(arra2)

np.float64(4.320493798938574)

In [52]:
np.prod(arra1,arra3)

TypeError: only integer scalar arrays can be converted to a scalar index

6. Indexing and slicing
7. reshaping
8. Stacking
9. spliting

In [53]:
arra3

array([[20.        , 18.92857143, 17.85714286, 16.78571429, 15.71428571],
       [14.64285714, 13.57142857, 12.5       , 11.42857143, 10.35714286],
       [ 9.28571429,  8.21428571,  7.14285714,  6.07142857,  5.        ]])

In [54]:
# first row then comluns
arra3[1,4]

np.float64(10.357142857142858)

In [55]:
arra3[::2,4]

array([15.71428571,  5.        ])

In [56]:
arra3[::,3]

array([16.78571429, 11.42857143,  6.07142857])