In [2]:
print("HEllo Numpy? Let's get started!")

HEllo Numpy? Let's get started!


# Numpy Day-01
1. Creaitn numpy array
    i. np.array <br>
    ii. 1D array<br>
    iii. 2D array<br>
    iv. 3D array<br>
    v. dtype<br>
    vi. np.arange<br>
    vii. reshape<br>
    viii. np.ones <br>
    ix. np.zeros<br>
    x. np.random<br>
    xi. np.linespace<br>
    xii. np.identity
2. Array Attributes
    i. ndim<br>
    ii.shape<br>
    iii. size<br>
    iv. itemsize<br>
    v. dtype
3. Changing Datatype
    i. astype(np.int32)
4. Array operations
    i. Scalar operations<br>
    ii. Arithmatic operation (+,-,**,/,%)<br>
    iii. rational (==,!=,<=,>=)<br>
    iv. Vector<br>
5. Array Functions
    i. max/min/sum/mod<br>
    ii. mean/median/mode/std/var<br>
    iii. Trigonmatirc function<br>
    iv. dot product<br>
    v. log and exponents<br>
    vi. round/floor/ceil<br>
6. Indexing and slicing
7. reshaping
8. Stacking
9. spliting



In [3]:
print("Hello wolrd")

Hello wolrd


In [4]:
# 1. Creating Numpy array

# import numpy
import numpy as np
print(np.__version__)

2.3.5


In [5]:
# create an array using np.array
np.array([10,40,30,50,60,100,30,20])
# 1D array or vector
d1 = np.array([40,20,90,80,30])
d1

array([40, 20, 90, 80, 30])

In [6]:
# 2D array = MAtrix = row and column format
mat = np.array([[10,20,30,40],[50,60,79],[5,6,7]])
mat

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [7]:
mat = np.array([[10,20,30,40],[50,60,79,55],[5,6,7,60]])
mat

array([[10, 20, 30, 40],
       [50, 60, 79, 55],
       [ 5,  6,  7, 60]])

In [8]:
# check dimention of mat array
mat.ndim

2

In [9]:
# how many rows and coumns?
mat.shape

(3, 4)

In [10]:
# make empty array
em = []

In [11]:
for i in range(1,10):
    em.append(i)
em

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
# convert list into array
nparray = np.array(em)
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 3D array
array3d = np.array([[[10,20,30,10],[40,50,60,43],[70,80,90,34]],[[1,2,3,4],[5,6,7,8],[9,10,1,12]],[[10,20,30,10],[40,50,60,43],[70,80,90,34]]])
array3d.shape

(3, 3, 4)

In [14]:
array3d1 = np.array([[[10,20,30,10],[40,50,60,43]],[[1,2,3,4],[5,6,7,8]],[[10,20,30,10],[40,50,60,43]]])
# 3 rows ---3d, 2 rows---2D, 4 columns --- 2D
array3d1.shape

(3, 2, 4)

In [15]:
# reshape 3D columns into 2D
array3d1.reshape(2,4,3)

array([[[10, 20, 30],
        [10, 40, 50],
        [60, 43,  1],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [ 8, 10, 20],
        [30, 10, 40],
        [50, 60, 43]]])

In [16]:
array3d1.reshape(4,2,3)

array([[[10, 20, 30],
        [10, 40, 50]],

       [[60, 43,  1],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [ 8, 10, 20]],

       [[30, 10, 40],
        [50, 60, 43]]])

In [17]:
# anyhow all products number = total itemsize
array3d1.reshape(4,3,2)

array([[[10, 20],
        [30, 10],
        [40, 50]],

       [[60, 43],
        [ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8],
        [10, 20]],

       [[30, 10],
        [40, 50],
        [60, 43]]])

In [18]:
# check how many iteams
array3d1.size

24

In [19]:
# check data types
array3d.dtype

dtype('int64')

In [20]:
# checnge dtaype 
array3d = array3d.astype("int32")
array3d

array([[[10, 20, 30, 10],
        [40, 50, 60, 43],
        [70, 80, 90, 34]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10,  1, 12]],

       [[10, 20, 30, 10],
        [40, 50, 60, 43],
        [70, 80, 90, 34]]], dtype=int32)

In [21]:
array3d.dtype

dtype('int32')

In [22]:
# Different ways of make array
# zero arra--- all values are zero
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# one array --- all values are one
ones = np.ones((4,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# identity array --- only digonal value 1 rest of them 0
ideti = np.identity((10,4))
ideti

TypeError: 'tuple' object cannot be interpreted as an integer

In [25]:
# identity is a squre shape matrix that's the reason it does not allow tuple
ideti = np.identity((4))
ideti

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# as like python range start,end,step
arange = np.arange(1,18,2)
arange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [ ]:
# make random number from 0 to 1 array
rarray  = np.random.random(2)
rarray

array([0.01358483, 0.65622067])

In [ ]:
# create an array between 10 to 5 , 10 numbers
np.linspace(10,5,10)

array([10.        ,  9.44444444,  8.88888889,  8.33333333,  7.77777778,
        7.22222222,  6.66666667,  6.11111111,  5.55555556,  5.        ])

In [ ]:
# It's just crerate lower to upper value number not upper to lower value
np.arange(-10,30,3)

array([-10,  -7,  -4,  -1,   2,   5,   8,  11,  14,  17,  20,  23,  26,
        29])

In [40]:
# using reshape
np.linspace(10,5,10).reshape(2,5)

array([[10.        ,  9.44444444,  8.88888889,  8.33333333,  7.77777778],
       [ 7.22222222,  6.66666667,  6.11111111,  5.55555556,  5.        ]])

 ### Array operations
    i. Scalar operations<br>
    ii. Arithmatic operation (+,-,**,/,%)<br>
    iii. rational (==,!=,<=,>=)<br>
    iv. Vector<br>

In [41]:
arr1 = np.random.random(12).reshape(3,4)
arr1

array([[0.31971741, 0.3908367 , 0.63762675, 0.36115963],
       [0.6749829 , 0.32790805, 0.54313452, 0.97556789],
       [0.62548461, 0.61732926, 0.66783131, 0.02862442]])

In [42]:
# apply scalar opetion on arr1
5*arr1

array([[1.59858706, 1.95418351, 3.18813374, 1.80579817],
       [3.37491451, 1.63954023, 2.71567259, 4.87783945],
       [3.12742307, 3.08664632, 3.33915653, 0.14312212]])

In [ ]:
# Add 5 for every elements of array
5+arr1

array([[5.31971741, 5.3908367 , 5.63762675, 5.36115963],
       [5.6749829 , 5.32790805, 5.54313452, 5.97556789],
       [5.62548461, 5.61732926, 5.66783131, 5.02862442]])

In [45]:
# arithmatich operations
arra2 = np.arange(2,20,3).reshape(2,3)
arra2

array([[ 2,  5,  8],
       [11, 14, 17]])

In [46]:
arra3 = np.random.random(6).reshape(2,3)
arra3

array([[0.12886904, 0.70356755, 0.13441706],
       [0.46308069, 0.89083858, 0.72063687]])

In [47]:
# now add arra2 + arra3
arra2 + arra3

array([[ 2.12886904,  5.70356755,  8.13441706],
       [11.46308069, 14.89083858, 17.72063687]])

In [48]:
arra2 * arra3

array([[ 0.25773807,  3.51783773,  1.07533646],
       [ 5.09388759, 12.47174007, 12.2508268 ]])

In [49]:
arra2 ** arra3

array([[ 1.09343619,  3.10293452,  1.32248483],
       [ 3.03563005, 10.49578843,  7.703833  ]])

In [50]:
arra2 / arra3

array([[15.51963187,  7.10663821, 59.51625602],
       [23.75395959, 15.71552958, 23.59024455]])

In [51]:
arra2 % arra3

array([[0.06696446, 0.07502718, 0.06939362],
       [0.34914413, 0.63742135, 0.42535198]])

In [52]:
arra2 - arra3

array([[ 1.87113096,  4.29643245,  7.86558294],
       [10.53691931, 13.10916142, 16.27936313]])

In [53]:
# rational operatiors
arra2 == 3

array([[False, False, False],
       [False, False, False]])

In [54]:
arra2 >= arra3

array([[ True,  True,  True],
       [ True,  True,  True]])

In [55]:
# vectors operators
varray = arra3**arra2
varray

array([[1.66072285e-02, 1.72396716e-01, 1.06570025e-07],
       [2.10001981e-04, 1.98237683e-01, 3.81223911e-03]])

### 5. Array Functions
    i. max/min/sum/mod<br>
    ii. mean/median/mode/std/var<br>
    iii. Trigonmatirc function<br>
    iv. dot product<br>
    v. log and exponents<br>
    vi. round/floor/ceil<br>

In [57]:
arra1 = np.random.random(15).reshape(3,5)
arra2 = np.arange(10,25,1).reshape(3,5)
arra3 = np.linspace(20,5,15).reshape(3,5)

In [61]:
print("Array 1",arra1)
print("Array 2",arra2)
print("Array 3",arra3)

Array 1 [[0.63208733 0.25673861 0.08403558 0.0416574  0.24116662]
 [0.25943089 0.02320839 0.26507432 0.62225709 0.09196754]
 [0.52840964 0.87060748 0.10306656 0.1447729  0.57819069]]
Array 2 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Array 3 [[20.         18.92857143 17.85714286 16.78571429 15.71428571]
 [14.64285714 13.57142857 12.5        11.42857143 10.35714286]
 [ 9.28571429  8.21428571  7.14285714  6.07142857  5.        ]]


In [62]:
np.sum(arra1)

np.float64(4.742671024669576)

In [63]:
np.max(arra2)

np.int64(24)

In [64]:
np.mean(arra3)

np.float64(12.5)

In [65]:
np.round(arra3)

array([[20., 19., 18., 17., 16.],
       [15., 14., 12., 11., 10.],
       [ 9.,  8.,  7.,  6.,  5.]])

In [66]:
np.median(arra3)

np.float64(12.5)

In [67]:
np.std(arra2)

np.float64(4.320493798938574)

In [70]:
np.prod(arra1,arra3)

TypeError: only integer scalar arrays can be converted to a scalar index

6. Indexing and slicing
7. reshaping
8. Stacking
9. spliting

In [71]:
arra3

array([[20.        , 18.92857143, 17.85714286, 16.78571429, 15.71428571],
       [14.64285714, 13.57142857, 12.5       , 11.42857143, 10.35714286],
       [ 9.28571429,  8.21428571,  7.14285714,  6.07142857,  5.        ]])

In [ ]:
# first row then comluns
arra3[1,4]

np.float64(10.357142857142858)

In [75]:
arra3[::2,4]

array([15.71428571,  5.        ])

In [76]:
arra3[::,3]

array([16.78571429, 11.42857143,  6.07142857])