In [2]:
print("HEllo Numpy? Let's get started!")

HEllo Numpy? Let's get started!


# Numpy Day-01
1. Creaitn numpy array
    i. np.array <br>
    ii. 1D array<br>
    iii. 2D array<br>
    iv. 3D array<br>
    v. dtype<br>
    vi. np.arange<br>
    vii. reshape<br>
    viii. np.ones <br>
    ix. np.zeros<br>
    x. np.random<br>
    xi. np.linespace<br>
    xii. np.identity
2. Array Attributes
    i. ndim<br>
    ii.shape<br>
    iii. size<br>
    iv. itemsize<br>
    v. dtype
3. Changing Datatype
    i. astype(np.int32)
4. Array operations
    i. Scalar operations<br>
    ii. Arithmatic operation (+,-,**,/,%)<br>
    iii. rational (==,!=,<=,>=)<br>
    iv. Vector<br>
5. Array Functions
    i. max/min/sum/mod<br>
    ii. mean/median/mode/std/var<br>
    iii. Trigonmatirc function<br>
    iv. dot product<br>
    v. log and exponents<br>
    vi. round/floor/ceil<br>
6. Indexing and slicing
7. reshaping
8. Stacking
9. spliting



In [3]:
print("Hello wolrd")

Hello wolrd


In [4]:
# 1. Creating Numpy array

# import numpy
import numpy as np
print(np.__version__)

2.3.5


In [5]:
# create an array using np.array
np.array([10,40,30,50,60,100,30,20])
# 1D array or vector
d1 = np.array([40,20,90,80,30])
d1

array([40, 20, 90, 80, 30])

In [6]:
# 2D array = MAtrix = row and column format
mat = np.array([[10,20,30,40],[50,60,79],[5,6,7]])
mat

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [7]:
mat = np.array([[10,20,30,40],[50,60,79,55],[5,6,7,60]])
mat

array([[10, 20, 30, 40],
       [50, 60, 79, 55],
       [ 5,  6,  7, 60]])

In [8]:
# check dimention of mat array
mat.ndim

2

In [9]:
# how many rows and coumns?
mat.shape

(3, 4)

In [10]:
# make empty array
em = []

In [11]:
for i in range(1,10):
    em.append(i)
em

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
# convert list into array
nparray = np.array(em)
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 3D array
array3d = np.array([[[10,20,30,10],[40,50,60,43],[70,80,90,34]],[[1,2,3,4],[5,6,7,8],[9,10,1,12]],[[10,20,30,10],[40,50,60,43],[70,80,90,34]]])
array3d.shape

(3, 3, 4)

In [14]:
array3d1 = np.array([[[10,20,30,10],[40,50,60,43]],[[1,2,3,4],[5,6,7,8]],[[10,20,30,10],[40,50,60,43]]])
# 3 rows ---3d, 2 rows---2D, 4 columns --- 2D
array3d1.shape

(3, 2, 4)

In [15]:
# reshape 3D columns into 2D
array3d1.reshape(2,4,3)

array([[[10, 20, 30],
        [10, 40, 50],
        [60, 43,  1],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [ 8, 10, 20],
        [30, 10, 40],
        [50, 60, 43]]])

In [16]:
array3d1.reshape(4,2,3)

array([[[10, 20, 30],
        [10, 40, 50]],

       [[60, 43,  1],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [ 8, 10, 20]],

       [[30, 10, 40],
        [50, 60, 43]]])

In [17]:
# anyhow all products number = total itemsize
array3d1.reshape(4,3,2)

array([[[10, 20],
        [30, 10],
        [40, 50]],

       [[60, 43],
        [ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8],
        [10, 20]],

       [[30, 10],
        [40, 50],
        [60, 43]]])

In [18]:
# check how many iteams
array3d1.size

24

In [19]:
# check data types
array3d.dtype

dtype('int64')

In [20]:
# checnge dtaype 
array3d = array3d.astype("int32")
array3d

array([[[10, 20, 30, 10],
        [40, 50, 60, 43],
        [70, 80, 90, 34]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10,  1, 12]],

       [[10, 20, 30, 10],
        [40, 50, 60, 43],
        [70, 80, 90, 34]]], dtype=int32)

In [21]:
array3d.dtype

dtype('int32')

In [22]:
# Different ways of make array
# zero arra--- all values are zero
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# one array --- all values are one
ones = np.ones((4,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# identity array --- only digonal value 1 rest of them 0
ideti = np.identity((10,4))
ideti

TypeError: 'tuple' object cannot be interpreted as an integer

In [25]:
# identity is a squre shape matrix that's the reason it does not allow tuple
ideti = np.identity((4))
ideti

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# as like python range start,end,step
arange = np.arange(1,18,2)
arange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])